---
kernel: ""           # Leave blank for the base linux kernel (Supports 'zen', 'hardened' & 'lts')
linux-firmware: true # Install linux-firmware

hostname: "excalibur"

aur:
  enable: true
  helper: "paru"

boot:
  bootloader: "grub"
  efi: true
  # @TODO add bootloader configuration options


packages:
  - "networkmanager"
  - "openssh"
  - "reflector"
  - "neovim"
  
services:
  - "NetworkManager"
  - "sshd"
  - "reflector.timer"


clock:
  timezone: "US/Mountain" # Time zone from /usr/share/zoneinfo/
  hardware-utc: true      # Use the '--utc' option on 'hwclock --systohc'
  enable-ntp: true        # Enable systemd-timesyncd 

locales:
  locale-conf: "en_US.UTF-8" # Locale to be added to /etc/locale.conf

  gen-locales:               # Locales to be uncommented in /etc/locale.gen
    - "en_US.UTF-8 UTF-8"
    - "en_US ISO-8859-1"
    - "ja_JP.UTF-8 UTF-8"


user-config:
  # Might add more general user configuration

  users:
    mason:
      - name: "mason"
      - comment: "Mason"
      - home: "/home/mason"
      - groups:
        - "wheel"


disks:
  disk1:
    path: "/dev/vda"

    partitions:
      part1:
        start-sector: "0"
        end-sector: "+1G"
        type-code: "ef00"
        label: "EFI Partition"
      part2:
        start-sector: "0"
        end-sector: "+4G"
        type-code: "8200"
        label: "Swap Partition"
      part3:
        start-sector: "0"
        end-sector: "0"
        type-code: "8300"
        label: "Root Partition"
