---
drives:
  vda:
    device-path: "/dev/vda"
    partitions:
      efi:
        size: "256M"
        type-code: "ef00"
        partition-label: "EFI Partition"
      raidswap1:
        size: "2G"
        type-code: "fd00"
        partition-label: "Raid Swap 1"
      raidroot1:
        size: "10G"
        type-code: "fd00"
        partition-label: "Raid Root 1"
      raidhome1:
        type-code: "fd00"
        partition-label: "Raid Home 1"
  vdb:
    device-path: "/dev/vdb"
    partitions:
      raidswap2:
        start-sector: "+256M"
        end-sector: "+2G"
        type-code: "fd00"
        partition-label: "Raid Swap 2"
      raidroot2:
        size: "10G"
        type-code: "fd00"
        partition-label: "Raid Root 2"
      raidhome2:
        type-code: "fd00"
        partition-label: "Raid Home 2"

raid:
  swap:
    devices:
      - raidswap1
      - raidswap2
    array-name: "RAIDSWAP"
    level: 0
  root:
    devices:
      - raidroot1
      - raidroot2
    array-name: "RAIDROOT"
    level: 1
  home:
    devices:
      - raidhome1
      - raidhome2
    array-name: "RAIDHOME"
    level: 1

crypt:
  swap:
    crypt-label: "CRYPTSWAP"
  home:
    crypt-label: "CRYPTHOME"

filesystems:
  efi:
    filesystem: "efi"
    label: "EFI BOOT"
    mountpoint: "/efi"
  swap:
    filesystem: "swap"
    label: "SWAP"
  root:
    filesystem: "ext4"
    label: "ROOT"
    mountpoint: "/"
  home:
    filesystem: "ext4"
    label: "HOME"
    mountpoint: "/home"

users:
  mason:
    shell: "/bin/bash"
    comment: "Mason"
    home: "/home/mason"
    groups:
      - "wheel"