---
packages:
  kernel: "linux-zen" # Which kernel to install
  firmware: true      # Install linux-firmware

  network-manager:
    package: "networkmanager" # Acutal package name 
    service: "NetworkManager" # Name to enable service

  ssh:
    package: "openssh" # Actual package name
    service: "sshd"    # Name to enable service

  text-editor: "neovim"

  additional-packages: # Any additional packages go here (each entry gets its own line)
    - "reflector"

clock:
  timezone: "US/Mountain"
  hardware-utc: true
  enable-ntp: true

locales:
  locale-conf: "en_US.UTF-8"
  gen-locales:
    - "en_US.UTF-8 UTF-8"
    - "en_US ISO-8859-1"
    - "ja_JP.UTF-8 UTF-8"