---
kernel: ""           # Leave blank for the base linux kernel (Supports 'zen', 'hardened' & 'lts')
linux-firmware: true # Install linux-firmware

hostname: "excalibur"

aur:
  enable: true
  helper: "paru"

boot:
  bootloader: "grub"
  efi: true
  # @TODO add bootloader configuration options


packages:
  - "networkmanager"
  - "openssh"
  - "reflector"
  - "neovim"
  
services:
  - "NetworkManager"
  - "sshd"
  - "reflector.timer"


clock:
  timezone: "US/Mountain" # Time zone from /usr/share/zoneinfo/
  hardware-utc: true      # Use the '--utc' option on 'hwclock --systohc'
  enable-ntp: true        # Enable systemd-timesyncd 

locales:
  locale-conf: "en_US.UTF-8" # Locale to be added to /etc/locale.conf

  gen-locales:               # Locales to be uncommented in /etc/locale.gen
    - "en_US.UTF-8 UTF-8"
    - "en_US ISO-8859-1"
    - "ja_JP.UTF-8 UTF-8"


user-config:

  users:
    mason:
      - name: "mason"
      - comment: "Mason"
      - home: "/home/mason"
      - groups:
        - "wheel"


drives:

  nvme1:
    device-path: "/dev/vda"
    gpt: true
    
    partitions:

      efi:
        size: "4G"
        type-code: "ef00"
        partition-label: "EFI Partition"

      swap:
        size: "16G"
        type-code: "8200"
        partition-label: "Swap Partition"

      root:
        partition-label: "Root Partition"

  nvme2:
    device-path: "/dev/vdb"
    gpt: true

    partitions:
      home:
        size: "0"
        type-code: "8300"
        partition-label: "Home Partition"


filesystems:

  efi:
    filesystem: "efi"
    label: "EFI BOOT"

  swap:
    filesystem: "swap"
    label: "SWAP"

  root:
    filesystem: "ext4"
    label: "ROOT"

  home:
    filesystem: "xfs"
    label: "HOME"

