---
kernel: "linux-zen"
linux-firmware: true

boot:
  bootloader: "refind"
  efi: true

  # @TODO add bootloader configuration options

ssh:
  package-name: "openssh"
  service-name: "sshd"

network:
  package-name: "networkmanager"
  service-name: "NetworkManager"

additional-packages:
  - "reflector" # @TODO more reflector configuration options
  - "neovim"

clock:
  timezone: "US/Mountain" # Time zone from /usr/share/zoneinfo/
  hardware-utc: true      # Whether or not to set hardware clock using UTC
  enable-ntp: true        # Whether or not to enable NTP time synchonization 

locales:
  locale-conf: "en_US.UTF-8" # Locale to be added to /etc/locale.conf

  gen-locales:               # Locales to be uncommented in /etc/locale.gen
    - "en_US.UTF-8 UTF-8"
    - "en_US ISO-8859-1"
    - "ja_JP.UTF-8 UTF-8"

user-config:
  # Might add more general user configuration

  users:
    mason:
      - name: "mason"
      - comment: "Mason"
      - home: "/home/mason"
      - groups:
        - "wheel"
